<?php
/**
 * QsClientScript class file.
 *
 * @author Paul Klimov <pklimov@quartsoft.com>
 * @link http://www.quartsoft.com/
 * @copyright Copyright &copy; 2010-2013 QuartSoft ltd.
 * @license http://www.quartsoft.com/license/
 */

/**
 * QsClientScript is an extension of {@link CClientScript}, which manages JavaScript and CSS stylesheets for views.
 * This extension changes the meta tags management.
 * @see CClientScript
 *
 * @author Paul Klimov <pklimov@quartsoft.com>
 * @package qs.web
 */
class QsClientScript extends CClientScript {
	/**
	 * Registers a meta tag that will be inserted in the head section (right before the title element) of the resulting page.
	 *
	 * <b>Note:</b>
	 * This method will invoke {@link registerMetaTag()} with the id generated by given Meta tag options.
	 * This means: if you call this method with the same meta tag name and options but different content multiply times -
	 * only one meta tag will be rendered with the last given content.
	 *
	 * <b>Example:</b>
	 * <pre>
	 *    $cs->registerMetaTag('example', 'description', null, array('lang' => 'en'));
	 *    $cs->registerMetaTag('beispiel', 'description', null, array('lang' => 'de')); // register new meta tag
	 *    $cs->registerMetaTag('overridden', 'description', null, array('lang' => 'en')); // overwrite meta tag
	 * </pre>
	 * @param string $content content attribute of the meta tag
	 * @param string $name name attribute of the meta tag. If null, the attribute will not be generated
	 * @param string $httpEquiv http-equiv attribute of the meta tag. If null, the attribute will not be generated
	 * @param array $options other options in name-value pairs (e.g. 'scheme', 'lang')
	 * @return CClientScript the CClientScript object itself.
	 */
	public function registerMetaTagUnique($content, $name=null, $httpEquiv=null, $options=array()) {
		$idParts = $options;
		$idParts['name'] = $name;
		$idParts['http-equiv'] = $httpEquiv;
		ksort($idParts, SORT_STRING);
		$id = serialize($idParts);
		return $this->registerMetaTag($content, $name, $httpEquiv, $options, $id);
	}
}
