<?php
/**
 * ImageTranslationDynamicImageWidget class file.
 *
 * @author Paul Klimov <pklimov@quartsoft.com>
 * @link http://www.quartsoft.com/
 * @copyright Copyright &copy; 2010-2013 QuartSoft ltd.
 * @license http://www.quartsoft.com/license/
 */

/**
 * ImageTranslationDynamicImageWidget is a widget, which allows to display current image translation,
 * depending on language value, which is set up by HTML input field.
 *
 * @see ImageTranslation
 * @see ImagetranslationModule
 *
 * @property CModel $model public alias of {@link _model}.
 * @property string $languageInputId public alias of {@link _languageInputId}.
 * @property array $languages public alias of {@link _languages}.
 *
 * @author Paul Klimov <pklimov@quartsoft.com>
 * @package qs.i18n.modules.imagetranslation
 */
class ImageTranslationDynamicImageWidget extends CWidget {
	/**
	 * @var CModel image translation model.
	 */
	protected $_model = null;
	/**
	 * @var string id of the HTML element, which should be a source of the language value.
	 * If not set this parameter will be initialized using {@link CHtml} methods from the {@link model} model.
	 */
	protected $_languageInputId = '';
	/**
	 * @var array list of language locale codes.
	 */
	protected $_languages = array();

	public function setModel(CModel $model) {
		$this->_model = $model;
		return true;
	}

	public function getModel() {
		return $this->_model;
	}

	public function setLanguageInputId($languageInputId) {
		if (!is_string($languageInputId)) {
			throw new CException('"' . get_class($this) . '::languageInputId" should be a string!');
		}
		$this->_languageInputId = $languageInputId;
		return true;
	}

	public function getLanguageInputId() {
		if (empty($this->_languageInputId)) {
			$this->initLanguageInputId();
		}
		return $this->_languageInputId;
	}

	public function setLanguages(array $languages) {
		$this->_languages = $languages;
		return true;
	}

	public function getLanguages() {
		if (empty($this->_languages)) {
			$this->initLanguages();
		}
		return $this->_languages;
	}

	/**
	 * Initializes {@link languageInputId} value, using {@link CHtml} methods.
	 * @return boolean success.
	 */
	protected function initLanguageInputId() {
		if (is_object($this->_model)) {
			$modelAttribute = 'language';
			$languageInputName = CHtml::resolveName($this->_model, $modelAttribute);
			$languageInputId = CHtml::getIdByName($languageInputName);
			$this->_languageInputId = $languageInputId;
			return true;
		}
		return false;
	}

	/**
	 * Initializes {@link languages} value, using 'languageManager' component.
	 * @return boolean success.
	 */
	protected function initLanguages() {
		$module = $this->getImageTranslationModule();
		$languageManager = $module->getComponent('languageManager');
		$languageModels = $languageManager->getLanguages();
		$languages = array();
		if (is_array($languageModels)) {
			foreach ($languageModels as $languageModel) {
				$languages[] = $languageModel->locale_code;
			}
		}
		$this->_languages = $languages;
		return true;
	}

	/**
	 * Returns image translation module.
	 * @return CModule image translation module.
	 */
	public function getImageTranslationModule() {
		$module = null;
		$currentController = Yii::app()->getController();
		if (is_object($currentController)) {
			$module = $currentController->getModule();
		}
		if (!is_object($module)) {
			$module = Yii::app()->getModule('imagetranslation');
		}
		return $module;
	}

	/**
	 * Initializes the widget.
	 * This method is called by {@link CBaseController::createWidget}
	 * and {@link CBaseController::beginWidget} after the widget's
	 * properties have been initialized.
	 */
	public function init() {
		$model = $this->getModel();
		if (!is_object($model)) {
			throw new CException('"' . get_class($this) . '::model" should be setup!');
		}
		$this->echoImage();
		$this->echoJavaScript();
	}

	/**
	 * Outputs an image HTML tag, which should display image translation image.
	 * @return void
	 */
	protected function echoImage() {
		$model = $this->getModel();

		$imageHtmlOptions = array(
			'id' => $this->getId(),
			'width' => $model->width,
			'height' => $model->height,
		);
		echo CHtml::image($model->fetchUrl(), 'Current Image', $imageHtmlOptions);
	}

	/**
	 * Outputs JavaScript code, which should update an image, generated by (@link echoImage()).
	 * @return void
	 */
	protected function echoJavaScript() {
		Yii::app()->getClientScript()->registerCoreScript('jquery');

		$model = $this->getModel();

		$caseStrings = array();
		foreach ($this->getLanguages() as $language ) {
			$caseStrings[] = "case '{$language}': imageSrc = '" . $model->fetchUrl($language) . "'; break;";
		}

		$updateImageCode = "
			var language = this.value;
			var imageSrc = '';
			switch (language) { " . implode(' ', $caseStrings) . " }
			$('#" . $this->getId() . "').attr('src', imageSrc);
		";

		$id = $this->getLanguageInputId();
		$event = 'change';
		$jsScript = "$('body').on('{$event}','#{$id}',function(){".$updateImageCode."})";
		echo CHtml::script($jsScript);

		$jsScript = "$('#{$id}').trigger('{$event}')";
		echo CHtml::script($jsScript);
	}
}
